# tox (https://tox.readthedocs.io/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
skipsdist = True
envlist =
    py38
    coverage
    bandit
skip_missing_interpreters = true

[testenv]
description = run tests
passenv =
    TOXENV
    CI
    TRAVIS
    TRAVIS_*
    CODECOV_*
deps =
    virtualenv!=20.0.22
    pre-commit
    pytest
    pytest-aiohttp
    coverage
    codecov
changedir = {env:HOME}/tmp
commands =
	git clone https://github.com/mitre/caldera.git --recursive {env:HOME}/tmp
	rm -rf {env:HOME}/tmp/plugins/atomic
	python -m pip install -r {env:HOME}/tmp/requirements.txt
	cp -R {toxinidir} {env:HOME}/tmp/plugins/atomic
    coverage run -p -m pytest --tb=short --rootdir={env:HOME}/tmp -Werror plugins/atomic/tests
allowlist_externals =
    git
    rm
    cp

[testenv:py38]
description = run tests
deps =
    virtualenv!=20.0.22
    pre-commit
    pytest
    pytest-aiohttp
    coverage
    codecov
changedir = {env:HOME}/tmp
commands =
	git clone https://github.com/mitre/caldera.git --recursive {env:HOME}/tmp
	rm -rf {env:HOME}/tmp/plugins/atomic
	python -m pip install -r {env:HOME}/tmp/requirements.txt
	cp -R {toxinidir} {env:HOME}/tmp/plugins/atomic
    coverage run -p -m pytest --tb=short --rootdir={env:HOME}/tmp {env:HOME}/tmp/plugins/atomic/tests
allowlist_externals =
    git
    rm
    cp

[testenv:coverage]
deps =
    coverage
skip_install = true
changedir = {env:HOME}/tmp
commands =
    coverage combine
    coverage html
    coverage report

[testenv:coverage-ci]
deps =
    coveralls
    coverage
skip_install = true
changedir = {env:HOME}/tmp
commands =
    python {toxinidir}/scripts/check_coverage.py
