name: Code Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - python-version: 3.7
            toxenv: py37
          - python-version: 3.8
            toxenv: py38
          - python-version: 3.10
            toxenv: py310
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade virtualenv
          pip install tox
      - name: Run tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox
